---
- name: Download Diagnostic pdf
  hosts: F5_Lab
  gather_facts: False

  tasks:

    - name: Generate API access token
      # Client ID and Secret are valid for 6 months.
      # Auth token is valid for 30 mins.
      shell: |
        curl --request POST --url https://identity.account.f5.com/oauth2/ausp95ykc80HOU7SQ357/v1/token -H "accept: application/json" -H "authorization: Basic "{{ ihealth_basic }}"" -H "cache-control: no-cache" -H "content-type: application/x-www-form-urlencoded" --data "grant_type=client_credentials&scope=ihealth"
      register: payload
      delegate_to: localhost

    - set_fact:
        bearer_token: "{{ payload.stdout }}"

    - name: GET qkview id
      shell: |
        curl --url https://ihealth2-api.f5.com/qkview-analyzer/api/qkviews -H "Authorization: Bearer "{{ bearer_token.access_token }}"" -H "Accept: application/vnd.f5.ihealth.api" --user-agent "AnsibleClient"
      register: response_message
      delegate_to: localhost

    - set_fact:
        qkview_id: "{{ response_message.stdout | regex_search('<id>([0-9]+)</id>', '\\1') }}"

    - name: Download diagnostics pdf
      shell: |
        curl --url https://ihealth2-api.f5.com/qkview-analyzer/api/qkviews/"{{ qkview_id[0] }}"/diagnostics.pdf -H "Authorization: Bearer "{{ bearer_token.access_token }}"" -H "Accept: application/vnd.f5.ihealth.api" --user-agent "AnsibleClient" --output "{{ '/var/tmp/' + inventory_hostname + '-diagnostics.pdf' }}"
      delegate_to: localhost